#!/usr/bin/env python3
from pathlib import Path


def replace(path, old, new):
    p=Path(path); s=p.read_text(encoding='utf-8')
    if old not in s: raise SystemExit(f'missing anchor in {path}: {old[:80]}')
    p.write_text(s.replace(old,new,1),encoding='utf-8')

# Round 7 defect ledger was frozen before this correction phase:
# R7-01 Future evidence/scenario/alert stores had no explicit retention cleanup.
# R7-02 Research workspaces persisted with expires_at=NULL despite expiry governance.
# R7-03 FUT-029 engine accepted workspaces with no expiry metadata.
# R7-04 Automated QA did not enforce these retention/expiry invariants.

replace('src/Infrastructure/Activator.php',
"        add_option('smai_quarantine_retention_days', '14', '', false);\n",
"        add_option('smai_quarantine_retention_days', '14', '', false);\n        add_option('smai_future_run_retention_days', '180', '', false);\n        add_option('smai_future_scenario_retention_days', '365', '', false);\n        add_option('smai_future_alert_retention_days', '180', '', false);\n        add_option('smai_future_incident_retention_days', '365', '', false);\n")

replace('src/Infrastructure/RetentionRunner.php',
"        $quarantineDays = max(1, min(90, (int) get_option('smai_quarantine_retention_days', 14)));\n        $eventCutoff = gmdate('Y-m-d H:i:s', time() - $eventDays * DAY_IN_SECONDS);\n        $modelCutoff = gmdate('Y-m-d H:i:s', time() - $modeledDays * DAY_IN_SECONDS);\n        $quarantineCutoff = gmdate('Y-m-d H:i:s', time() - $quarantineDays * DAY_IN_SECONDS);\n",
"        $quarantineDays = max(1, min(90, (int) get_option('smai_quarantine_retention_days', 14)));\n        $futureRunDays = max(1, min(730, (int) get_option('smai_future_run_retention_days', 180)));\n        $futureScenarioDays = max(1, min(730, (int) get_option('smai_future_scenario_retention_days', 365)));\n        $futureAlertDays = max(1, min(365, (int) get_option('smai_future_alert_retention_days', 180)));\n        $futureIncidentDays = max(1, min(730, (int) get_option('smai_future_incident_retention_days', 365)));\n        $eventCutoff = gmdate('Y-m-d H:i:s', time() - $eventDays * DAY_IN_SECONDS);\n        $modelCutoff = gmdate('Y-m-d H:i:s', time() - $modeledDays * DAY_IN_SECONDS);\n        $quarantineCutoff = gmdate('Y-m-d H:i:s', time() - $quarantineDays * DAY_IN_SECONDS);\n        $futureRunCutoff = gmdate('Y-m-d H:i:s', time() - $futureRunDays * DAY_IN_SECONDS);\n        $futureScenarioCutoff = gmdate('Y-m-d H:i:s', time() - $futureScenarioDays * DAY_IN_SECONDS);\n        $futureAlertCutoff = gmdate('Y-m-d H:i:s', time() - $futureAlertDays * DAY_IN_SECONDS);\n        $futureIncidentCutoff = gmdate('Y-m-d H:i:s', time() - $futureIncidentDays * DAY_IN_SECONDS);\n")

replace('src/Infrastructure/RetentionRunner.php',
"        $wpdb->query($wpdb->prepare(\n            \"DELETE FROM `{$this->db->table('jobs')}` WHERE state='completed' AND completed_at<%s\",\n            gmdate('Y-m-d H:i:s', time() - 30 * DAY_IN_SECONDS)\n        ));\n",
"        $wpdb->query($wpdb->prepare(\n            \"DELETE FROM `{$this->db->table('jobs')}` WHERE state='completed' AND completed_at<%s\",\n            gmdate('Y-m-d H:i:s', time() - 30 * DAY_IN_SECONDS)\n        ));\n\n        // Future-40 derivative evidence is explicitly retention-bound. Governance\n        // configuration and published transparency records are not silently purged.\n        $wpdb->query($wpdb->prepare(\"DELETE FROM `{$this->db->table('future_runs')}` WHERE created_at<%s\", $futureRunCutoff));\n        $wpdb->query($wpdb->prepare(\"DELETE FROM `{$this->db->table('scenario_models')}` WHERE updated_at<%s\", $futureScenarioCutoff));\n        $wpdb->query($wpdb->prepare(\"DELETE FROM `{$this->db->table('intelligence_alerts')}` WHERE updated_at<%s\", $futureAlertCutoff));\n        $wpdb->query($wpdb->prepare(\"DELETE FROM `{$this->db->table('analytics_incidents')}` WHERE state IN ('resolved','closed') AND updated_at<%s\", $futureIncidentCutoff));\n        $wpdb->query($wpdb->prepare(\"UPDATE `{$this->db->table('research_workspaces')}` SET state='expired',updated_at=%s WHERE expires_at IS NOT NULL AND expires_at<%s AND state NOT IN ('expired','revoked')\", $now, $now));\n        $wpdb->query($wpdb->prepare(\"DELETE FROM `{$this->db->table('research_workspaces')}` WHERE state IN ('expired','revoked') AND updated_at<%s\", $modelCutoff));\n")

replace('src/Domain/Future40Engine.php',
"        $title=trim((string)($input['title']??''));$purpose=trim((string)($input['purpose']??''));$datasets=self::stringList($input['approved_aggregate_datasets']??[]);\n        return ['valid'=>$title!==''&&$purpose!==''&&$datasets!==[],'title'=>$title,'purpose'=>$purpose,'datasets'=>$datasets,'raw_data_allowed'=>false];\n",
"        $title=trim((string)($input['title']??''));$purpose=trim((string)($input['purpose']??''));$datasets=self::stringList($input['approved_aggregate_datasets']??[]);$expiresOn=trim((string)($input['expires_on']??''));$expiryValid=self::validDate($expiresOn);\n        return ['valid'=>$title!==''&&$purpose!==''&&$datasets!==[]&&$expiryValid,'title'=>$title,'purpose'=>$purpose,'datasets'=>$datasets,'expires_on'=>$expiryValid?$expiresOn:null,'raw_data_allowed'=>false];\n")

replace('src/Domain/FutureArtifactStore.php',
"        $title=Text::truncate(trim((string)($input['title']??'')),190);$purpose=Text::truncate(trim((string)($input['purpose']??'')),500);$datasets=$input['approved_aggregate_datasets']??[];\n        if($title===''||$purpose===''||!is_array($datasets)||$datasets===[])return new WP_Error('smai_future_research_metadata_required','Research workspace requires title, purpose and approved aggregate datasets.',['status'=>400]);\n        $uuid=Uuid::v4();$now=$this->db->now();$ok=$this->db->wpdb()->insert($this->db->table('research_workspaces'),[\n            'workspace_uuid'=>$uuid,'title'=>$title,'purpose'=>$purpose,'datasets_json'=>Json::canonical(array_values(array_map('strval',$datasets))),'state'=>'draft','owner_user_id'=>$actorUserId,'approved_by'=>null,'expires_at'=>null,'row_version'=>1,'created_at'=>$now,'updated_at'=>$now,\n",
"        $title=Text::truncate(trim((string)($input['title']??'')),190);$purpose=Text::truncate(trim((string)($input['purpose']??'')),500);$datasets=$input['approved_aggregate_datasets']??[];$expiresOn=trim((string)($input['expires_on']??''));\n        if($title===''||$purpose===''||!is_array($datasets)||$datasets===[])return new WP_Error('smai_future_research_metadata_required','Research workspace requires title, purpose and approved aggregate datasets.',['status'=>400]);\n        $tz=new \\DateTimeZone('UTC');$expiry=\\DateTimeImmutable::createFromFormat('!Y-m-d',$expiresOn,$tz);$today=new \\DateTimeImmutable('today',$tz);\n        if($expiry===false||$expiry->format('Y-m-d')!==$expiresOn||$expiry<=$today||$expiry>$today->modify('+365 days'))return new WP_Error('smai_future_research_expiry_required','Research workspace expiry must be a valid future date within 365 days.',['status'=>400]);\n        $expiresAt=$expiry->format('Y-m-d 23:59:59');$uuid=Uuid::v4();$now=$this->db->now();$ok=$this->db->wpdb()->insert($this->db->table('research_workspaces'),[\n            'workspace_uuid'=>$uuid,'title'=>$title,'purpose'=>$purpose,'datasets_json'=>Json::canonical(array_values(array_map('strval',$datasets))),'state'=>'draft','owner_user_id'=>$actorUserId,'approved_by'=>null,'expires_at'=>$expiresAt,'row_version'=>1,'created_at'=>$now,'updated_at'=>$now,\n")

replace('tests/future40.php',
"'CF05-FUT-029'=>['title'=>'Aggregate study','purpose'=>'quality','approved_aggregate_datasets'=>['d1']],",
"'CF05-FUT-029'=>['title'=>'Aggregate study','purpose'=>'quality','approved_aggregate_datasets'=>['d1'],'expires_on'=>'2026-12-31'],")
replace('tests/future40.php',
"$r=Future40Engine::evaluate('CF05-FUT-030',['control_n'=>10,'variant_n'=>10,'control_rate'=>1.2,'variant_rate'=>0.5]);",
"$r=Future40Engine::evaluate('CF05-FUT-029',['title'=>'x','purpose'=>'y','approved_aggregate_datasets'=>['d1']]); f40_truth(($r['valid']??true)===false,'Research workspace must require governed expiry metadata.');\n$r=Future40Engine::evaluate('CF05-FUT-030',['control_n'=>10,'variant_n'=>10,'control_rate'=>1.2,'variant_rate'=>0.5]);")

p=Path('scripts/future40-check.py');s=p.read_text(encoding='utf-8')
anchor="# Review-5 API/governance invariants.\n"
if anchor not in s: raise SystemExit('missing future40 check anchor')
insert="""# Review-7 privacy/retention invariants.\nretention=text('src/Infrastructure/RetentionRunner.php')\nactivator=text('src/Infrastructure/Activator.php')\nartifact=text('src/Domain/FutureArtifactStore.php')\nfor token in ['smai_future_run_retention_days','smai_future_scenario_retention_days','smai_future_alert_retention_days','smai_future_incident_retention_days']:\n    if token not in activator or token not in retention: errors.append(f'review7_retention_option_missing:{token}')\nfor token in [\"table('future_runs')\",\"table('scenario_models')\",\"table('intelligence_alerts')\",\"table('research_workspaces')\"]:\n    if token not in retention: errors.append(f'review7_retention_target_missing:{token}')\nif 'expires_on' not in engine: errors.append('review7_research_expiry_engine_missing')\nif 'smai_future_research_expiry_required' not in artifact or \"'expires_at'=>$expiresAt\" not in artifact:\n    errors.append('review7_research_expiry_persistence_missing')\n"""
s=s.replace(anchor,insert+anchor,1);p.write_text(s,encoding='utf-8')

Path('docs/REVIEW-ROUND-7.md').write_text("""# CF-05 Review Round 7 — Privacy, Retention and Research Expiry\n\nAudit completed before corrections. Defect ledger was frozen before code changes.\n\n## Defects found\n1. Future run evidence, scenario models and intelligence alerts had no explicit retention cleanup.\n2. Resolved Future analytics incidents had no retention cleanup.\n3. Research workspaces were persisted with `expires_at = NULL`, contradicting governed expiry.\n4. FUT-029 accepted research workspace metadata without an expiry field and QA did not guard these rules.\n\n## Corrections\n- Added bounded Future-40 retention options and cleanup paths.\n- Expired research workspaces are state-marked, then purged after the modeled-retention window.\n- FUT-029 now requires `expires_on`; active persistence requires a future UTC date no more than 365 days ahead.\n- Added automated invariants and regression coverage.\n\nStatus boundary: repository/source correction only; no staging/live claim.\n""",encoding='utf-8')
print('Review-7 retention and research-expiry corrections applied.')
